version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apakahleaked_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - apakahleaked

  nginx:
    image: nginx:alpine
    container_name: apakahleaked_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - apakahleaked

  db:
    image: mysql:8.0
    container_name: apakahleaked_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - apakahleaked

networks:
  apakahleaked:
    driver: bridge

volumes:
  dbdata:
